# Build configuration for Railway
[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["npm install", "npm install -g serve"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "serve dist -s -l $PORT"

